# Generated by Django 5.1.3 on 2024-12-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
